name: sk-ide
version: '0.0'
summary: IDE for Skript
description: ...
grade: devel
confinement: devmode

apps:
  run:
    command: desktop-launch $SNAP/bin/Sk-IDE

parts:
  sk-ide:
    after: [desktop-glib-only]
    plugin: gradle
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      export PATH="/usr/lib/jvm/java-8-openjdk-amd64/bin:$PATH"
      gradle clean
      gradle build
    install: |
      tar xvf build/distributions/Sk-IDE-shadow-*.tar -C $SNAPCRAFT_PART_INSTALL/ --strip-components=1
    build-packages:
      - tar
      - openjdk-8-jdk
      - openjfx
    stage-packages:
      - tar
      - openjdk-8-jdk
      - openjfx
